language: go
before_deploy:
- cd toc && ./toc-linux
deploy:
  provider: pages
  skip-cleanup: true
  target-branch: master
  github-token: $GH_TOKEN # https://docs.travis-ci.com/user/environment-variables#Defining-Variables-in-Repository-Settings
  keep-history: true
  verbose: true
  on:
    branch: master
    repo: softleader/softleader-training-course
